import React, { useMemo, useRef, useState } from 'react'
import { FeatureGroup, GeoJSON, MapContainer, TileLayer } from 'react-leaflet'
import 'leaflet/dist/leaflet.css'
import 'leaflet-draw/dist/leaflet.draw.css'
import { EditControl } from 'react-leaflet-draw'
import { LatLngExpression } from 'leaflet'
import axios from 'axios'
import type { AxiosError, AxiosResponse } from 'axios'
import turfArea from '@turf/area'
import { useNavigate } from 'react-router-dom'
import FieldTechnicalDetails from './FieldTechnicalDetails'

type RegisterLandResponse = { land_id: string }
type GenerateGridsResponse = { count: number; grid_ids: number[] }

type FeatureCollection = {
  type: 'FeatureCollection'
  features: Array<{ type: 'Feature'; properties: any; geometry: any }>
}

function isClosedPolygon(geometry: any): boolean {
  if (!geometry || geometry.type !== 'Polygon') return false
  const ring = geometry.coordinates?.[0]
  if (!Array.isArray(ring) || ring.length < 4) return false
  const first = ring[0]
  const last = ring[ring.length - 1]
  return Array.isArray(first) && Array.isArray(last) && first.length >= 2 && last.length >= 2 && first[0] === last[0] && first[1] === last[1]
}

function isLonLatInRange(geometry: any): boolean {
  if (!geometry || geometry.type !== 'Polygon') return false
  const ring = geometry.coordinates?.[0]
  if (!Array.isArray(ring) || ring.length === 0) return false
  for (const pt of ring) {
    if (!Array.isArray(pt) || pt.length < 2) return false
    const lon = pt[0]
    const lat = pt[1]
    if (typeof lon !== 'number' || typeof lat !== 'number') return false
    if (lon < -180 || lon > 180 || lat < -90 || lat > 90) return false
  }
  return true
}

function formatAreaSqm(value: number | null): string {
  if (!value || !Number.isFinite(value)) return '–'
  const rounded = Math.round(value)
  return rounded.toLocaleString() + ' m²'
}

export default function MapEditor() {
  const fgRef = useRef<any>(null)
  const center: LatLngExpression = [0, 0]
  const navigate = useNavigate()

  const [owner, setOwner] = useState('')
  const [cropType, setCropType] = useState('')
  const [polygonGeometry, setPolygonGeometry] = useState<any | null>(null)
  const [status, setStatus] = useState<'idle' | 'submitting' | 'done' | 'error'>('idle')
  const [error, setError] = useState<string | null>(null)
  const [landId, setLandId] = useState<string | null>(null)
  const [landOverlay, setLandOverlay] = useState<any | null>(null)
  const [gridOverlay, setGridOverlay] = useState<FeatureCollection | null>(null)

  const polygonClosed = useMemo(() => isClosedPolygon(polygonGeometry), [polygonGeometry])
  const coordsInRange = useMemo(() => (polygonGeometry ? isLonLatInRange(polygonGeometry) : false), [polygonGeometry])
  const areaSqm = useMemo(() => {
    if (!landOverlay) return null
    try {
      return turfArea(landOverlay as any)
    } catch {
      return null
    }
  }, [landOverlay])

  const canSubmit = useMemo(
    () => owner.trim().length > 0 && !!polygonGeometry && polygonClosed && coordsInRange && status !== 'submitting',
    [owner, polygonGeometry, polygonClosed, coordsInRange, status]
  )

  const onCreated = (e: any) => {
    const layer = e.layer
    const geojson = layer.toGeoJSON()
    setPolygonGeometry(geojson.geometry)
    setLandOverlay({ type: 'Feature', properties: {}, geometry: geojson.geometry })
    setGridOverlay(null)
    setLandId(null)
    setError(null)
    setStatus('idle')
  }

  const onDeleted = () => {
    setPolygonGeometry(null)
    setLandOverlay(null)
    setGridOverlay(null)
    setLandId(null)
    setError(null)
    setStatus('idle')
  }

  const submitLand = async () => {
    if (!canSubmit || !polygonGeometry) return
    setStatus('submitting')
    setError(null)
    try {
      const res = await axios.post<any, AxiosResponse<RegisterLandResponse>>('/lands/', {
        owner: owner.trim(),
        crop_type: cropType.trim() || null,
        geometry: polygonGeometry,
      })
      const newLandId = res.data.land_id
      setLandId(newLandId)

      // Auto-generate grids (10m) after registration
      try {
        await axios.post<any, AxiosResponse<GenerateGridsResponse>>('/grids/generate', {
          land_id: newLandId,
          cell_size_m: 10.0,
        })
      } catch {
        // Grids will be generated by the processing pipeline if this fails
      }

      // Trigger background processing pipeline
      try {
        await axios.post(`/dashboard/${newLandId}/process`)
      } catch {
        // Processing may fail for satellite data reasons; dashboard will still work
      }

      setStatus('done')
      // Navigate to dashboard
      navigate(`/dashboard/${newLandId}`)
    } catch (err) {
      const ax = err as AxiosError<any>
      const detail = (ax.response?.data as any)?.detail
      setError(detail || ax.message)
      setStatus('error')
    }
  }

  return (
    <div className="w-full">
      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        <div className="md:col-span-1">
          <div className="rounded-lg border bg-white p-4">
            <div className="text-lg font-semibold">Land registration</div>

            <div className="mt-3 grid grid-cols-1 gap-3">
              <div className="grid grid-cols-3 gap-3">
                <div>
                  <div className="text-sm font-semibold">Polygon closure</div>
                  <div className="mt-1 inline-flex items-center rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-800">
                    {polygonGeometry ? (polygonClosed ? 'Valid' : 'Invalid') : 'Invalid / missing'}
                  </div>
                </div>
                <div>
                  <div className="text-sm font-semibold">Coordinate range</div>
                  <div className="mt-1 inline-flex items-center rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-800">
                    {polygonGeometry ? (coordsInRange ? 'OK' : 'Out of range') : 'Out of range'}
                  </div>
                </div>
                <div>
                  <div className="text-sm font-semibold">Area (sq. meters)</div>
                  <div className="mt-1 text-sm text-gray-700">{formatAreaSqm(areaSqm)}</div>
                </div>
              </div>
            </div>

            <div className="mt-3">
              <label className="block text-sm font-medium">Farmer name</label>
              <input
                className="mt-1 w-full rounded-md border px-3 py-2"
                value={owner}
                onChange={(e) => setOwner(e.target.value)}
                placeholder="e.g., Amina Hassan"
              />
            </div>
            <div className="mt-3">
              <label className="block text-sm font-medium">Crop type (optional)</label>
              <input
                className="mt-1 w-full rounded-md border px-3 py-2"
                value={cropType}
                onChange={(e) => setCropType(e.target.value)}
                placeholder="e.g., maize"
              />
            </div>

            <div className="mt-4 text-sm text-gray-700">Draw your field on the map, then press Register.</div>

            <FieldTechnicalDetails geometry={polygonGeometry} />

            {error && (
              <div className="mt-3 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">
                {error}
              </div>
            )}

            {landId && status === 'done' && (
              <div className="mt-3 rounded-md border border-green-200 bg-green-50 p-3 text-sm text-green-800">
                Land registered. ID: <span className="font-mono">{landId}</span>
              </div>
            )}

            <button
              className="mt-4 w-full rounded-md bg-green-600 px-4 py-2 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50"
              disabled={!canSubmit}
              onClick={submitLand}
            >
              {status === 'submitting' ? 'Registering…' : 'Register Land'}
            </button>
          </div>
        </div>

        <div className="md:col-span-2">
          <div className="h-[70vh] overflow-hidden rounded-lg border">
            <MapContainer center={center} zoom={2} style={{ height: '100%', width: '100%' }}>
              <TileLayer
                url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
                attribution="Tiles © Esri — Source: Esri, Maxar, Earthstar Geographics, and the GIS User Community"
              />

              {gridOverlay && (
                <GeoJSON
                  data={gridOverlay as any}
                  style={() => ({ weight: 1, fillOpacity: 0.05 })}
                />
              )}

              {landOverlay && (
                <GeoJSON
                  data={landOverlay as any}
                  style={() => ({ weight: 3, fillOpacity: 0.08 })}
                />
              )}

              <FeatureGroup ref={fgRef}>
                <EditControl
                  position="topright"
                  onCreated={onCreated}
                  onDeleted={onDeleted}
                  draw={{
                    rectangle: false,
                    circle: false,
                    marker: false,
                    circlemarker: false,
                    polyline: false,
                  }}
                />
              </FeatureGroup>
            </MapContainer>
          </div>
        </div>
      </div>
    </div>
  )
}
